# Project details
sonar.projectKey=rubice_frontend
sonar.projectName=Rubicr Frontend
sonar.projectVersion=1.0

# Source and exclusions
sonar.sources=.
sonar.exclusions=node_modules/**,.next/**,__tests__/**,**/*.test.tsx,**/*.test.ts,**/*.js,**/*.ts,app/**,lib/**,**/*.json,sonar-project.properties,stories/**

# Code coverage paths
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# SonarQube server details
sonar.host.url=http://localhost:9000
sonar.login=sqp_3d3dcea4795c7a605b2df3047bc8b590f22d9d45