import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { headers } from 'next/headers';
import { Toaster } from 'react-hot-toast';
import ClientProvider from '../components/ClientProvider/ClientProvider';
import { UserProvider } from '../components/Context/userProvider';
import { AuthLayout } from '../components/Layout/AuthLayout';
import { ModalProvider } from '../components/Modal/Context';
// import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css';
import './plate.css';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

// const inter = Inter({
//   subsets: ['latin'],
// });

// const interItalic = localFont({
//   src: './fonts/Inter-Italic-VariableFont_opsz,wght.woff',
//   variable: '--font-inter-italic',
//   weight: '100 900',
// });
const interVariable = localFont({
  src: './fonts/Inter-VariableFont_opsz,wght.woff',
  variable: '--font-inter-variable',
  weight: '100 200 300 400 500 600 700 800 900',
});

export const metadata: Metadata = {
  title: 'Rubicr ',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const host = headersList.get('host');
  const slug = host?.split('.')[0] ?? '';

  return (
    <html lang="en">
      <body className={interVariable.className}>
        <ClientProvider>
          <ModalProvider>
            <UserProvider>
              <AuthLayout slug={slug}>
                {children}
              </AuthLayout>
            </UserProvider>
          </ModalProvider>
        </ClientProvider>
        <Toaster
          position="bottom-center"
          gutter={8}
          toastOptions={{
            success: {
              duration: 3000,
              style: {
                background: '#FBA900',
                color: '#232538',
              },
            },
            error: {
              duration: 5000,
              style: {
                background: 'red',
                color: 'white',
              },
            },
          }}
        />
      </body>
    </html>
  );
}
