import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { headers } from 'next/headers';
import { Toaster } from 'react-hot-toast';
import Providers from '../components/Providers';
import { AuthLayout } from '../components/Layout/AuthLayout';
import './globals.css';
import './plate.css';

const interVariable = localFont({
  src: './fonts/Inter-VariableFont_opsz,wght.woff',
  variable: '--font-inter-variable',
  weight: '100 200 300 400 500 600 700 800 900',
});

export const metadata: Metadata = {
  title: 'Rubicr ',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const host = headersList.get('host');
  const slug = host?.split('.')[0] ?? '';

  return (
    <html lang="en">
      <body className={interVariable.className}>
        <Providers>
          <AuthLayout slug={slug}>
            {children}
          </AuthLayout>
        </Providers>
        <Toaster
          position="bottom-center"
          gutter={8}
          toastOptions={{
            success: {
              duration: 3000,
              style: {
                background: '#FBA900',
                color: '#232538',
              },
            },
            error: {
              duration: 5000,
              style: {
                background: 'red',
                color: 'white',
              },
            },
          }}
        />
      </body>
    </html>
  );
}
