import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { headers } from 'next/headers';
import { Toaster } from 'react-hot-toast';
import Providers from '../components/Providers';
import { AuthLayout } from '../components/Layout/AuthLayout';
import './globals.css';
import './plate.css';
import { auth } from '@/lib/auth';

const interVariable = localFont({
  src: './fonts/Inter-VariableFont_opsz,wght.woff',
  variable: '--font-inter-variable',
  weight: '100 200 300 400 500 600 700 800 900',
});

export const metadata: Metadata = {
  title: 'Rubicr ',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const headersList = headers();
  const host = headersList.get('host');
  const slug = host?.split('.')[0] ?? '';

  return (
    <html lang="en">
      <body className={interVariable.className}>
        <Providers session={session}>
          <AuthLayout slug={slug}>{children}</AuthLayout>
        </Providers>
        <Toaster
          position="top-right"
          gutter={8}
          toastOptions={{
            duration: 3000,
            style: {
              background: '#0f766e',
              color: '#fff',
              borderRadius: '0.5rem',
            },
            success: {
              duration: 3000,
              iconTheme: {
                primary: '#FFFFFF',
                secondary: '#0f766e',
              },
              style: {
                background: '#0f766e',
                color: '#fff',
              },
            },
            error: {
              duration: 4000,
              iconTheme: {
                primary: '#FFFFFF',
                secondary: '#ef4444',
              },
              style: {
                background: '#363636',
                color: '#fff',
              },
            },
            loading: {
              iconTheme: {
                primary: '#FFFFFF',
                secondary: '#0f766e',
              },
            },
          }}
        />
      </body>
    </html>
  );
}
